FROM golang:1.23-alpine AS builder

RUN apk update && apk upgrade --no-cache

RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

FROM alpine:3.20
RUN apk update && \
    apk upgrade --no-cache && \
    apk add --no-cache ca-certificates

COPY --from=builder /go/bin/migrate /usr/local/bin/migrate

ENTRYPOINT ["migrate"]